<a href="https://colab.research.google.com/github/Anakinskywalker-14bby/Machine_learning_libraries/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Functions lesson:
Find the factorial of a number

Finding the factorial using loops

In [ ]:
number = int(input('Enter a number to find it factorial: '))

factorial = 1

if number == 0:
  print('The factorial of 0 is 1')

else:
  for i in range(1, number + 1):  #range(1,6) -> 1,2,3,4,5
    factorial = factorial * i     #1*2*3*4*5

  print('The factorial of', number, 'is', factorial)


Enter a number to find it factorial: 5
The factorial of 5 is 120


Find the factorial using function

In [ ]:
def factorial_value(num):
  factorial = 1

  if num == 0:
    return factorial

  else:
    for i in range(1, num + 1):
      factorial = factorial * i
    return factorial

In [ ]:
print(factorial_value(0))
print(factorial_value(5))
print(factorial_value(10))

1
120
3628800


# NumPy - Numerial Python tutorial

In [ ]:
import numpy as np

List Vs Numpy - Time taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i + 5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.000615971000000215


Time taken by Numpy

In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5 # np_array = np_array + 5

end_time = process_time()

print(end_time - start_time)

0.00020157300000001044


# NumPy *Arrays*

In [ ]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
#np array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape #gives the rows and cols

(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
# arrays with floating points
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in Numpy arrays

In [ ]:
#create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy array of ones
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# array of a particular value
z = np.full((5,4),5) #last digit initializes the whole matrix with that specific number
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#create an identity matrix
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#create a numpy array with random values
#note all the values printed will be between 0 and 1 i.e real numbers
b = np.random.random((3,4))
print(b)

[[0.46150666 0.91420507 0.94189593 0.9059678 ]
 [0.92269923 0.11861919 0.55069917 0.49624453]
 [0.44747893 0.49390792 0.31272225 0.48356975]]


In [ ]:
# create a numpy array with random integer values
c = np.random.randint(10,100,(3,5)) # the first 2 numbers are the range and the bracket is teh matrix size
print(c)

[[32 40 30 44 82]
 [35 58 20 42 22]
 [95 69 73 22 79]]


In [ ]:
 #array of evenly spaced values --> specifying the number of values required
 #here u mention the number of vlaues
 d = np.linspace(10,30,6) #first 2 are teh range and the last digit is the number of vlaues
 print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
#array of evenly spaced values --> specifying the step
#last number in the range is ignored
e = np.arange(20,40,2)
print(e)

[20 22 24 26 28 30 32 34 36 38]


In [ ]:
#convert a list to a numpy array
list2 = [10,220,30,458,75]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[ 10 220  30 458  75]


numpy.ndarray

# Analyzing a numpy array

In [ ]:
c = np.random.randint(10,60,(5,5))
print(c)

[[57 17 41 35 44]
 [37 56 24 16 25]
 [42 24 54 55 16]
 [38 57 47 41 56]
 [40 52 54 49 50]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
#number of dimensions
print(c.ndim)

2


In [ ]:
#number of elements in the array
print(c.size)

25


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


# Mathematical operations on np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[7 3 8]
 [1 4 1]
 [0 4 2]]
[[18 14 13]
 [19 11 15]
 [19 14 13]]


In [ ]:
#method 1 for math operations
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[25 17 21]
 [20 15 16]
 [19 18 15]]
[[-11 -11  -5]
 [-18  -7 -14]
 [-19 -10 -11]]
[[126  42 104]
 [ 19  44  15]
 [  0  56  26]]
[[0.38888889 0.21428571 0.61538462]
 [0.05263158 0.36363636 0.06666667]
 [0.         0.28571429 0.15384615]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[1 2 7]
 [6 1 6]
 [4 6 0]]
[[13 14 16]
 [19 11 13]
 [15 13 14]]


In [ ]:
#method 2 for math operations
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[14 16 23]
 [25 12 19]
 [19 19 14]]
[[-12 -12  -9]
 [-13 -10  -7]
 [-11  -7 -14]]
[[ 13  28 112]
 [114  11  78]
 [ 60  78   0]]
[[0.07692308 0.14285714 0.4375    ]
 [0.31578947 0.09090909 0.46153846]
 [0.26666667 0.46153846 0.        ]]


# Array manipulation

In [ ]:
array = np.random.randint(0,10,(3,2))
print(array)
print(array.shape)

[[9 3]
 [7 2]
 [3 3]]
(3, 2)


In [ ]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 7 3]
 [3 2 3]]
(2, 3)


In [ ]:
array = np.random.randint(0,10,(3,2))
print(array)
print(array.shape)

[[4 1]
 [9 1]
 [8 4]]
(3, 2)


In [ ]:
#method 2 to find transpose
trans = array.T
print(trans)
print(trans.shape)

[[4 9 8]
 [1 1 4]]
(2, 3)


In [ ]:
#reshaping an array
a = np.random.randint(2,50,(4,5))
print(a)
print(a.shape)

[[10 13 15 12 48]
 [17 26 41 45 28]
 [27 26 30 13 40]
 [14 33 18 46 47]]
(4, 5)


In [ ]:
b = a.reshape(5,4)
print(b)
print(b.shape)

[[10 13 15 12]
 [48 17 26 41]
 [45 28 27 26]
 [30 13 40 14]
 [33 18 46 47]]
(5, 4)
