<a href="https://colab.research.google.com/github/Anakinskywalker-14bby/Numpy_learning/blob/main/Numpy_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Functions lesson:
Find the factorial of a number

Finding the factorial using loops

In [7]:
number = int(input('Enter a number to find it factorial: '))

factorial = 1

if number == 0:
  print('The factorial of 0 is 1')

else:
  for i in range(1, number + 1):  #range(1,6) -> 1,2,3,4,5
    factorial = factorial * i     #1*2*3*4*5

  print('The factorial of', number, 'is', factorial)


Enter a number to find it factorial: 5
The factorial of 5 is 120


Find the factorial using function

In [8]:
def factorial_value(num):
  factorial = 1

  if num == 0:
    return factorial

  else:
    for i in range(1, num + 1):
      factorial = factorial * i
    return factorial

In [10]:
print(factorial_value(0))
print(factorial_value(5))
print(factorial_value(10))

1
120
3628800


# NumPy - Numerial Python tutorial

In [11]:
import numpy as np

List Vs Numpy - Time taken

In [12]:
from time import process_time

Time taken by a list

In [16]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i + 5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.000615971000000215


Time taken by Numpy

In [17]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5 # np_array = np_array + 5

end_time = process_time()

print(end_time - start_time)

0.00020157300000001044


# NumPy *Arrays*

In [18]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [19]:
#np array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [20]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [21]:
a.shape #gives the rows and cols

(4,)

In [22]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [23]:
b.shape

(2, 4)

In [24]:
# arrays with floating points
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in Numpy arrays